# 对话设置
conversation_setting: 

  system: "现在你是一位金牌虚拟数字导游,你的名字叫{role_type},你的说话方式是{character}你能够根据游客提出的问题进行街道的相关问题解答"
  first_input: "我的{street_info},你需要根据我给出的街道信息撰写一段导游开头介绍的文案你需要尽可能的渲染街道,让游客有更大的兴趣游览街道"

# 数据集生成设置
data_generation_setting: 

  each_street_gen: 5

  # 每个conversation有多少个问答对
  each_conversation_qa: 5
  
  # 每个口播生成随机抽取三个亮点
  each_pick_hightlight: 3

  # 每个口播生成后随机抽取5个问题生成游客的提问
  each_pick_question: 5

  # 数据集生成 prompt
  dataset_gen_prompt: 现在你是一位金牌虚拟数字导游,你的名字叫{role_type},你的说话方式是{character}
                      我的{street_info},你需要根据我给出的街道信息撰写一段至少600字的导游开头介绍的文案你需要尽可能的渲染街道,让游客有更大兴趣游览街道。
                      输出文案后,结合街道信息站在游客的角度根据[{customer_question}]提出{each_conversation_qa}个问题并解答。
                      全部输出的信息使用我期望的 json 格式进行输出:{dataset_json_format}注意 json 一定要合法。

  # 数据生成 json 格式
  dataset_json_format: 
    '{
      "conversation": [
        {
          "output": 金牌虚拟数字导游开头介绍的文案,格式化一行输出,不要换行
        },
        {
          "input": 游客的问题,
          "output": 导游回答
        },
        {
          "input": 游客的问题,
          "output": 导游回答
        },
        ... 直到问题结束
      ]
    }'

# 街道相关知识生成设置
instruction_generation_setting: 
  # 街道相关知识生成 prompt
  dataset_gen_prompt: 我上传的是一个街道的基本信息,请帮我生成 markdwon 格式的说明书,需要包含街道的历史文化景点相关信息,美食介绍,酒店信息等越详细越好,只输出说明书即可


# 角色及其性格
role_type: 
  GOgo: 
    - 甜美
    - 可爱
    - 根据当地方言适当的幽默风趣
    - 熟练使用各种网络热门梗造句
    - 称呼客户为[宝子们]

# 街道信息结构体
street_info_struct: 
  - 街道名字是[{name}],
  - 街道的亮点是[{highlights}]

  # 游客通常会问关于某条街道的什么方面，这里我们选了十个
visitor_question_type: 
  - 历史与文化
  - 地标与建筑
  - 美食与餐饮
  - 购物与纪念品
  - 活动与娱乐
  - 交通与导航
  - 安全与注意事项
  - 拍照与摄影
  - 当地风俗与习惯
  - 其他服务与设施

street_list: 
  四川省: 
    成都市: 
      成都春熙路: [时尚潮流中心,美食聚集之地,网红打卡热点,购物中心林立,休闲氛围浓厚,夜生活丰富多彩]
      成都宽窄巷子: [古色古香街巷,传统小吃丰富,手工艺品精美,民俗文化浓厚,文艺气息弥漫,拍照圣地]
      成都锦里古街: [三国文化氛围,传统小吃遍地,古建筑风貌独特,手工艺品琳琅满目,民俗表演精彩,游客如织]
      成都太古里: [现代时尚商圈,国际品牌汇聚,潮流店铺众多,美食餐厅丰富,艺术装置打卡,购物体验极佳]
      成都东郊记忆: [文化创意园区,文艺演出频繁,艺术展览丰富,咖啡厅书店多,工业遗址改造,拍照打卡胜地]

    绵阳市: 
      绵阳涪城路: [商业繁华街道,美食小吃丰富,购物中心集中,电子产品集散地,城市文化展示,交通便利]
      绵阳临园干道: [城市主干道,绿化景观优美,商业设施齐全,休闲娱乐丰富,酒店住宿方便,公交线路发达]
      绵阳长虹大道: [科技产业聚集,电子企业众多,高等教育学府,美食餐厅遍布,交通便利快捷,城市发展新区]
      绵阳铁牛广场: [城市地标建筑,夜景灯光迷人,市民休闲广场,文化活动频繁,周边美食丰富,交通便利]
      绵阳江油李白故里: [历史文化景区,李白诗歌文化,古建筑风貌独特,诗词碑林丰富,民俗活动多样,文化氛围浓厚]

    自贡市: 
      自贡盐都大道: [城市主干道,盐文化展示,美食小吃丰富,购物中心集中,夜景灯光美丽,交通便利]
      自贡彩灯博物馆: [彩灯文化展示,精美彩灯展品,民俗文化浓厚,亲子游玩佳地,教育意义深远,拍照打卡点]
      自贡恐龙王国: [恐龙主题公园,恐龙化石展示,科普教育基地,游乐设施丰富,家庭游玩首选,交通便利]
      自贡南湖公园: [城市绿肺氧吧,湖光山色美景,市民休闲胜地,健身运动场所,儿童游乐区域,拍照圣地]
      自贡燊海井: [传统制盐工艺,历史文化遗址,井盐文化体验,手工制盐演示,科普教育基地,游客众多]

    攀枝花市: 
      攀枝花金沙江大道: [沿江风光大道,夜景灯光璀璨,商业设施齐全,美食餐厅丰富,城市发展新区,交通便利]
      攀枝花仁和广场: [市民休闲广场,绿化景观优美,文化活动频繁,周边美食丰富,公交线路发达,亲子游玩佳地]
      攀枝花炳草岗: [城市中心区域,商业繁华地段,购物中心集中,美食小吃丰富,酒店住宿方便,交通便利]
      攀枝花红格温泉: [天然温泉胜地,温泉水质优良,养生度假佳地,周边环境优美,住宿设施齐全,游客众多]
      攀枝花米易梯田: [田园风光美景,梯田景观独特,农耕文化体验,摄影拍照胜地,乡村旅游热门,空气清新]

    泸州市: 
      泸州江阳路: [城市主干道,商业繁华地段,美食小吃丰富,购物中心集中,酒店住宿方便,交通便利]
      泸州老窖旅游区: [白酒文化展示,泸州老窖酒厂,酿酒工艺体验,白酒品鉴购买,历史文化遗址,游客众多]
      泸州张坝桂圆林: [自然风光美景,桂圆树林茂密,市民休闲胜地,亲子游玩佳地,拍照打卡点,空气清新]
      泸州方山: [佛教文化名山,古建筑风貌独特,登山观景胜地,祈福求愿灵验,周边美食丰富,交通便利]
      泸州龙马潭公园: [城市绿肺氧吧,绿化景观优美,市民休闲胜地,健身运动场所,儿童游乐区域,文化活动频繁]
      
  江苏省: 
    南京市: 
      南京新街口: [繁华商业中心,时尚购物天堂,美食小吃丰富,地铁交通枢纽,历史文化悠久,游客络绎不绝]
      南京夫子庙: [古色古香街区,传统文化氛围,美食小吃遍地,秦淮河畔美景,夜景灯光璀璨,游客必游之地]
      南京中山陵: [历史文化遗址,孙中山陵寝地,雄伟建筑风貌,绿化景观优美,爱国主义教育,游客众多]
      南京湖南路: [时尚购物街区,国际品牌汇聚,潮流店铺众多,美食餐厅丰富,休闲娱乐齐全,交通便利]
      南京玄武湖公园: [城市绿肺氧吧,湖光山色美景,市民休闲胜地,健身运动场所,游船观光体验,拍照圣地]

    苏州市: 
      苏州观前街: [繁华商业中心,古老街巷风貌,美食小吃丰富,苏州特色商品,传统文化氛围,游客如织]
      苏州平江路: [水乡古镇风情,古建筑保存完好,美食小吃遍地,手工艺品精美,文艺气息浓厚,拍照打卡点]
      苏州拙政园: [古典园林艺术,精美园林建筑,绿化景观优美,历史文化底蕴,游客必游之地,拍照圣地]
      苏州金鸡湖: [现代城市湖泊,夜景灯光璀璨,湖滨休闲胜地,购物娱乐中心,高端酒店密布,商务活动频繁]
      苏州山塘街: [古色古香街区,传统文化氛围,美食小吃丰富,手工艺品琳琅满目,民俗表演精彩,游客众多]

    无锡市: 
      无锡中山路: [繁华商业中心,时尚购物天堂,美食小吃丰富,地铁交通枢纽,城市文化展示,游客络绎不绝]
      无锡鼋头渚: [太湖风景名胜,樱花观赏胜地,精美园林建筑,历史文化底蕴,游船观光体验,拍照圣地]
      无锡灵山大佛: [佛教文化景区,巨大佛像壮观,登山观景胜地,祈福求愿灵验,周边美食丰富,游客众多]
      无锡南禅寺: [古刹文化遗址,佛教文化氛围,美食小吃丰富,传统手工艺品,市民休闲胜地,交通便利]
      无锡锡惠公园: [城市绿肺氧吧,园林景观优美,市民休闲胜地,健身运动场所,儿童游乐区域,文化活动频繁]

    常州市: 
      常州南大街: [繁华商业中心,时尚购物天堂,美食小吃丰富,购物中心集中,城市文化展示,交通便利]
      常州天宁宝塔: [佛教文化景区,宝塔建筑雄伟,登塔观景胜地,祈福求愿灵验,周边美食丰富,游客众多]
      常州恐龙园: [恐龙主题公园,恐龙化石展示,游乐设施丰富,科普教育基地,家庭游玩首选,交通便利]
      常州青枫公园: [城市绿肺氧吧,绿化景观优美,市民休闲胜地,健身运动场所,儿童游乐区域,拍照圣地]
      常州淹城春秋乐园: [历史文化景区,春秋文化展示,游乐设施丰富,文艺表演精彩,亲子游玩佳地,游客如织]

    徐州市: 
      徐州彭城广场: [城市中心地标,繁华商业中心,美食小吃丰富,购物中心集中,地铁交通枢纽,市民休闲胜地]
      徐州云龙湖: [城市湖泊美景,湖光山色相映,市民休闲胜地,健身运动场所,游船观光体验,拍照圣地]
      徐州汉文化景区: [历史文化遗址,汉代文化展示,古墓群保护地,历史文化教育,游客众多]
      徐州淮海路: [繁华商业街区,时尚购物天堂,国际品牌汇聚,美食餐厅丰富,休闲娱乐齐全,交通便利]
      徐州云龙山: [城市山林景观,登山观景胜地,古建筑遗址,祈福求愿灵验,周边美食丰富,游客络绎不绝]

  安徽省: 
    合肥市: 
      合肥淮河路步行街: [繁华商业中心,时尚购物天堂,美食小吃丰富,历史文化底蕴,地铁交通枢纽,游客络绎不绝]
      合肥黄山路: [高校聚集区域,学术氛围浓厚,科技创新源地,美食小吃丰富,书店咖啡馆多,交通便利]
      合肥包公园: [历史文化遗址,包拯墓园所在,精美园林建筑,廉洁文化教育,游客必游之地,文化氛围浓厚]
      合肥天鹅湖: [城市湖泊美景,湖光山色相映,市民休闲胜地,夜景灯光璀璨,周边美食丰富,拍照打卡点]
      合肥三河古镇: [古镇风情体验,水乡特色明显,古建筑保存完好,美食小吃丰富,民俗表演精彩,游客如织]

    芜湖市: 
      芜湖中山路步行街: [繁华商业中心,时尚购物街区,美食小吃丰富,芜湖特色商品,传统文化氛围,交通便利]
      芜湖银湖路: [美食小吃聚集,夜市文化独特,本地生活体验,购物娱乐丰富,年轻活力四溢,交通便利]
      芜湖方特旅游度假区: [主题公园集群,游乐设施丰富,亲子游玩佳地,科技文化体验,游客众多,交通便利]
      芜湖赭山公园: [城市绿肺氧吧,山水景观优美,市民休闲胜地,健身运动场所,文化活动频繁,拍照打卡点]
      芜湖徽商博物馆: [徽商文化展示,文物展品丰富,科普教育基地,历史文化学习,游客参观体验,文化氛围浓厚]

    蚌埠市: 
      蚌埠淮河路: [繁华商业中心,时尚购物街区,美食小吃丰富,购物中心集中,城市文化展示,交通便利]
      蚌埠胜利路: [商业繁华地段,购物娱乐丰富,美食小吃众多,本地特色明显,交通便利,市民休闲胜地]
      蚌埠龙子湖: [城市湖泊美景,湖光山色相映,市民休闲胜地,健身运动场所,游船观光体验,拍照圣地]
      蚌埠蚌埠博物馆: [地方历史博物馆,文物展品丰富,科普教育基地,历史文化学习,游客参观体验,文化氛围浓厚]
      蚌埠花鼓灯嘉年华: [主题乐园体验,游乐设施丰富,亲子游玩佳地,文化表演精彩,游客众多,交通便利]

    淮南市: 
      淮南田家庵路: [繁华商业中心,时尚购物街区,美食小吃丰富,购物中心集中,城市文化展示,交通便利]
      淮南国庆路: [商业繁华街道,购物娱乐丰富,本地特色商品,美食小吃众多,交通便利,市民休闲胜地]
      淮南八公山: [历史文化名山,山水景观优美,登山观景胜地,历史文化教育,游客必游之地,拍照圣地]
      淮南龙湖公园: [城市绿肺氧吧,湖光山色美景,市民休闲胜地,健身运动场所,儿童游乐区域,文化活动频繁]
      淮南寿县古城墙: [古城防御工程,城墙保存完好,历史文化遗址,散步观光体验,拍照打卡热点,游客络绎不绝]

    安庆市: 
      安庆人民路: [繁华商业中心,时尚购物街区,美食小吃丰富,历史文化底蕴,购物娱乐齐全,交通便利]
      安庆菱湖路: [风景秀丽路段,菱湖公园相邻,市民休闲胜地,美食餐厅众多,散步慢跑佳地,文化氛围浓厚]
      安庆迎江寺: [佛教文化胜地,古老寺庙建筑,祈福求愿灵验,历史文化教育,游客参观体验,拍照圣地]
      安庆莲湖公园: [城市绿肺氧吧,湖光山色美景,市民休闲胜地,健身运动场所,儿童游乐设施,文化活动丰富]
      安庆安庆老街: [历史悠久街区,传统建筑风格,手工艺品丰富,美食小吃众多,游客必访之地,文化氛围浓厚]
  
  陕西省: 
    西安市: 
      碑林区回民街: [古老街区风貌,美食小吃云集,传统手艺展示,民族服饰琳琅,老字号店铺林立,人潮涌动不息]
      雁塔区小寨东路: [时尚购物街区,品牌店铺汇聚,潮流服饰多样,美食餐厅遍地,年轻人群聚集地,夜生活丰富多彩]
      莲湖区北大街: [历史与现代交融,特色小吃满街,传统与现代店铺并存,文化气息浓厚,交通便利快捷,购物娱乐方便]
      新城区长乐西路: [商业繁华地带,批发零售齐全,电子产品集中,时尚服饰多样,人流如织不绝,物流便捷高效]
      未央区凤城二路: [现代商业街区,高端品牌云集,商务办公集中,美食餐厅林立,休闲娱乐丰富,交通便利快捷]

    宝鸡市: 
      渭滨区经二路: [商业繁华中心,品牌店铺林立,时尚购物天堂,美食小吃丰富,交通四通八达,人流熙熙攘攘]
      金台区中山路: [历史街区风貌,传统建筑保存,地道小吃遍地,手工艺品独特,文化氛围浓厚,市民生活悠闲]
      陈仓区虢镇西街: [古镇街道风情,传统与现代并存,特色小吃诱人,手工艺品丰富,市民活动频繁,生活气息浓厚]
      凤翔县城关镇东大街: [县城繁华地带,商业活动频繁,特色小吃多样,日常用品齐全,交通便利快捷,市民生活便利]
      岐山县蔡家坡镇西三路: [工业小镇街道,工厂企业集中,商业服务完善,美食小吃丰富,交通便捷高效,工人生活便利]

    咸阳市: 
      秦都区人民路: [城市主干道,商业活动繁荣,品牌店铺众多,美食餐厅林立,公共交通发达,市民出行方便]
      渭城区新兴南路: [新兴商业街区,时尚潮流汇聚,年轻人群聚集地,美食小吃丰富,休闲娱乐多样,夜生活精彩纷呈]
      兴平市金城路: [县城中心街道,商业服务齐全,特色小吃诱人,手工艺品独特,市民活动频繁,生活气息浓厚]
      礼泉县建设路: [县城繁华地带,商业活动频繁,日常用品丰富,特色小吃多样,交通便利快捷,市民生活便利]
      乾县城关镇西大街: [古城街道风貌,传统建筑保存,地道小吃遍地,手工艺品丰富,文化氛围浓厚,市民生活悠闲]

    渭南市: 
      临渭区前进路: [城市主干道,商业活动繁荣,品牌店铺林立,美食餐厅遍地,公共交通发达,市民出行方便]
      韩城市金城区隍庙巷: [古城街道风情,传统建筑保存,地道小吃诱人,手工艺品独特,文化氛围浓厚,游客络绎不绝]
      华阴市华岳路: [城市主干道,商业服务完善,特色小吃丰富,日常用品齐全,交通便利快捷,市民生活便利]
      富平县莲湖大街: [县城中心街道,商业活动频繁,时尚购物天堂,美食小吃多样,休闲娱乐丰富,夜生活精彩纷呈]
      大荔县城关镇西环路: [县城繁华地带,商业服务齐全,特色小吃诱人,手工艺品丰富,市民活动频繁,生活气息浓厚]

    延安市: 
      宝塔区南大街: [城市主干道,商业活动繁荣,老字号店铺林立,地道小吃遍地,文化氛围浓厚,市民生活悠闲]
      延川县北大街: [县城中心街道,商业服务完善,特色小吃丰富,日常用品齐全,交通便利快捷,市民生活便利]
      子长县瓦窑堡镇中山街: [小镇街道风情,传统与现代并存,特色小吃诱人,手工艺品独特,市民活动频繁,生活气息浓厚]
      吴起县长征街: [红色文化街道,革命历史遗迹,特色小吃丰富,红色教育基地,文化氛围浓厚,游客络绎不绝]
      志丹县城关镇保安街: [县城繁华地带,商业活动频繁,品牌店铺众多,美食餐厅林立,休闲娱乐丰富,市民生活便利]

  湖南省:
    武汉市:
      武汉江汉路: [百年商业老街,国际品牌云集,美食小吃丰富,历史建筑林立,购物天堂美誉,人文气息浓厚]
      武汉光谷步行街: [现代科技商圈,时尚潮流汇聚,创意市集丰富,网红打卡圣地,娱乐休闲俱全,国际文化氛围]
      武汉户部巷: [传统小吃街巷,美食琳琅满目,地方特色鲜明,人气火爆旺地,文化底蕴深厚,游客络绎不绝]
      武汉东湖绿道: [湖畔骑行胜地,自然风光旖旎,健身休闲佳处,亲子游玩乐园,拍照打卡美景,交通便利通达]
      武汉黄鹤楼: [历史文化名楼,古建筑风貌独特,登高望远佳地,诗词文化丰富,拍照留念圣地,游客必访之处]
      
    宜昌市:
      宜昌夷陵大道: [城市主干道路,商业设施齐全,美食餐厅遍布,购物中心林立,交通便利快捷,城市文化展示]
      宜昌三峡大坝: [世界水利奇观,宏伟工程壮举,科普教育基地,观光游览胜地,拍照打卡热点,国民自豪之景]
      宜昌西陵峡: [长江三峡之一,自然风光壮丽,峡谷景观奇特,游船观光佳选,文化底蕴深厚,游客如织之地]
      宜昌CBD商务区: [现代商业中心,高楼大厦林立,国际品牌汇聚,商务活动频繁,休闲娱乐丰富,城市发展新区]
      宜昌车溪风景区: [民俗文化村落,传统手工艺展示,乡土风情浓郁,亲子游玩乐园,自然景观优美,文化体验丰富]
 
    襄阳市:
      襄阳古城墙: [千年古城遗迹,古建筑风貌独特,历史文化深厚,登高望远佳地,拍照打卡胜地,游客必游之处]
      襄阳北街: [传统商业街巷,美食小吃丰富,手工艺品精美,购物体验独特,文化氛围浓厚,人气旺盛之地]
      襄阳诸葛亮广场: [城市地标建筑,绿化景观优美,市民休闲胜地,文化活动频繁,交通便利快捷,亲子游玩佳地]
      襄阳岘山国家森林公园: [自然生态宝库,森林覆盖率高,登山观景胜地,健身运动佳处,空气清新宜人,拍照圣地]
      襄阳唐城影视基地: [仿唐建筑风格,影视拍摄基地,文化旅游景点,古装戏拍摄地,拍照打卡热点,游客争相探访]

    荆州市:
      荆州北京路: [城市主干道路,商业繁华地段,美食餐厅众多,购物中心集中,酒店住宿方便,交通便利快捷]
      荆州古城: [千年古城遗址,古城墙保存完好,历史文化深厚,游览观光胜地,拍照打卡热点,游客必到之处]
      荆州博物馆: [历史文化展馆,珍贵文物丰富,科普教育基地,文化交流活动,学术研究基地,游客学习佳地]
      荆州沙市中山公园: [城市绿肺氧吧,绿化景观优美,市民休闲胜地,健身运动场所,儿童游乐区域,文化活动丰富]
      荆州关公文化旅游区: [关公文化展示,巨型关公雕像,历史文化遗址,祈福求愿灵验,拍照打卡胜地,游客众多]
 
    黄冈市:
      黄冈赤壁大道: [城市主干道路,商业设施齐全,美食餐厅遍布,购物中心林立,交通便利快捷,城市发展新区]
      黄冈东坡赤壁: [历史文化遗址,东坡文化展示,古建筑风貌独特,登山观景佳地,拍照打卡热点,游客必访之处]
      黄冈遗爱湖公园: [城市生态公园,湖光山色美景,市民休闲胜地,健身运动场所,儿童游乐区域,文化活动频繁]
      黄冈黄冈师范学院: [高等教育学府,学术氛围浓厚,校园环境优美,文化活动丰富,图书馆资源丰富,学生学习佳地]
      黄冈英山温泉: [天然温泉胜地,温泉水质优良,养生度假佳地,周边环境优美,住宿设施齐全,游客络绎不绝]


  吉林省: 
    长春市: 
      朝阳区红旗街: [繁华商业中心,品牌旗舰店多,美食餐厅林立,文化活动频繁,交通便捷快速,购物体验优越]
      南关区重庆路: [历史街区风貌,特色小吃丰富,传统店铺众多,文化氛围浓厚,游客络绎不绝,交通便利快捷]
      宽城区胜利大街: [商业繁华地带,电子产品集中,时尚服饰多样,人流如织不绝,物流便捷高效,购物选择多样]
      绿园区西安大路: [城市主干道,商业活动繁荣,品牌店铺林立,美食餐厅遍地,公共交通发达,市民出行方便]
      二道区自由大路: [新兴商业街区,年轻人群聚集,潮流服饰多样,美食餐厅丰富,休闲娱乐多样,夜生活精彩纷呈]

    吉林市: 
      昌邑区吉林大街: [城市主干道,商业活动繁荣,品牌店铺众多,美食餐厅林立,公共交通发达,市民出行方便]
      船营区解放大路: [繁华商业中心,品牌旗舰店多,美食餐厅林立,文化活动频繁,交通便捷快速,购物体验优越]
      龙潭区汉阳街: [历史街区风貌,特色小吃丰富,传统店铺众多,文化氛围浓厚,游客络绎不绝,交通便利快捷]
      丰满区欧亚综合体: [现代商业街区,高端品牌云集,商务办公集中,美食餐厅林立,休闲娱乐丰富,交通便利快捷]
      桦甸市新华街: [县城繁华地带,商业活动频繁,特色小吃多样,日常用品齐全,交通便利快捷,市民生活便利]

    延边朝鲜族自治州: 
      延吉市公园路: [城市主干道,商业活动繁荣,品牌店铺众多,美食餐厅林立,公共交通发达,市民出行方便]
      图们市光明街: [历史街区风貌,特色小吃丰富,传统店铺众多,文化氛围浓厚,游客络绎不绝,交通便利快捷]
      敦化市沿江路: [现代商业街区,高端品牌云集,商务办公集中,美食餐厅林立,休闲娱乐丰富,交通便利快捷]
      珲春市新安街: [边境贸易中心,国际商品丰富,美食餐厅多样,文化活动频繁,交通便捷快速,购物体验优越]
      和龙市龙门街: [县城繁华地带,商业活动频繁,特色小吃多样,日常用品齐全,交通便利快捷,市民生活便利]

    白山市: 
      浑江区新建街: [城市主干道,商业活动繁荣,品牌店铺众多,美食餐厅林立,公共交通发达,市民出行方便]
      抚松县松江河街: [旅游服务中心,特色小吃丰富,旅游纪念品多,自然风光秀丽,游客络绎不绝,交通便利快捷]
      靖宇县正荣街: [历史街区风貌,特色小吃丰富,传统店铺众多,文化氛围浓厚,游客络绎不绝,交通便利快捷]
      长白县白山大街: [县城繁华地带,商业活动频繁,特色小吃多样,日常用品齐全,交通便利快捷,市民生活便利]
      江源区正阳街: [新兴商业街区,年轻人群聚集,潮流服饰多样,美食餐厅丰富,休闲娱乐多样,夜生活精彩纷呈]

    通化市: 
      东昌区滨江路: [城市主干道,商业活动繁荣,品牌店铺众多,美食餐厅林立,公共交通发达,市民出行方便]
      二道江区东明路: [历史街区风貌,特色小吃丰富,传统店铺众多,文化氛围浓厚,游客络绎不绝,交通便利快捷]
      辉南县朝阳街: [县城繁华地带,商业活动频繁,特色小吃多样,日常用品齐全,交通便利快捷,市民生活便利]
      集安市鸭绿江大街: [边境风情街道,特色小吃丰富,旅游纪念品多,自然风光秀丽,游客络绎不绝,交通便利快捷]
      柳河县胜利路: [新兴商业街区,年轻人群聚集,潮流服饰多样,美食餐厅丰富,休闲娱乐多样,夜生活精彩纷呈]

  广东省: 
    广州市: 
      天河区天河路: [繁华商业中心,品牌旗舰店多,美食餐厅林立,文化活动频繁,交通便捷快速,购物体验优越]
      越秀区北京路: [历史街区风貌,特色小吃丰富,传统店铺众多,文化氛围浓厚,游客络绎不绝,交通便利快捷]
      海珠区江南西路: [新兴商业街区,年轻人群聚集,潮流服饰多样,美食餐厅丰富,休闲娱乐多样,夜生活精彩纷呈]
      白云区黄石东路: [商业繁华地带,电子产品集中,时尚服饰多样,人流如织不绝,物流便捷高效,购物选择多样]
      荔湾区上下九步行街: [传统商业街区,特色小吃丰富,传统店铺众多,文化氛围浓厚,游客络绎不绝,交通便利快捷]

    深圳市: 
      罗湖区东门步行街: [繁华商业中心,品牌旗舰店多,美食餐厅林立,文化活动频繁,交通便捷快速,购物体验优越]
      福田区华强北路: [电子产品天堂,创新科技汇聚,时尚购物天堂,国际美食街,智能科技前沿,人流密集]
      南山区海岸城: [现代商业街区,高端品牌云集,商务办公集中,美食餐厅林立,休闲娱乐丰富,交通便利快捷]
      宝安区海雅缤纷城: [新兴商业街区,年轻人群聚集,潮流服饰多样,美食餐厅丰富,休闲娱乐多样,夜生活精彩纷呈]
      龙岗区龙城广场: [城市主干道,商业活动繁荣,品牌店铺众多,美食餐厅林立,公共交通发达,市民出行方便]

    佛山市: 
      禅城区祖庙路: [历史街区风貌,特色小吃丰富,传统店铺众多,文化氛围浓厚,游客络绎不绝,交通便利快捷]
      南海区千灯湖路: [现代商业街区,高端品牌云集,商务办公集中,美食餐厅林立,休闲娱乐丰富,交通便利快捷]
      顺德区大良清晖路: [传统商业街区,特色小吃丰富,传统店铺众多,文化氛围浓厚,游客络绎不绝,交通便利快捷]
      高明区荷城大道: [新兴商业街区,年轻人群聚集,潮流服饰多样,美食餐厅丰富,休闲娱乐多样,夜生活精彩纷呈]
      三水区西南大道: [城市主干道,商业活动繁荣,品牌店铺众多,美食餐厅林立,公共交通发达,市民出行方便]

    东莞市: 
      南城区鸿福路: [繁华商业中心,品牌旗舰店多,美食餐厅林立,文化活动频繁,交通便捷快速,购物体验优越]
      东城区东城中路: [历史街区风貌,特色小吃丰富,传统店铺众多,文化氛围浓厚,游客络绎不绝,交通便利快捷]
      虎门镇虎门大道: [商业繁华地带,电子产品集中,时尚服饰多样,人流如织不绝,物流便捷高效,购物选择多样]
      长安镇长青南路: [新兴商业街区,年轻人群聚集,潮流服饰多样,美食餐厅丰富,休闲娱乐多样,夜生活精彩纷呈]
      厚街镇厚街大道: [城市主干道,商业活动繁荣,品牌店铺众多,美食餐厅林立,公共交通发达,市民出行方便]

    珠海市: 
      香洲区拱北口岸: [繁华商业中心,品牌旗舰店多,美食餐厅林立,文化活动频繁,交通便捷快速,购物体验优越]
      吉大区情侣南路: [沿海风光旖旎,浪漫爱情圣地,海滩休闲娱乐,高端度假酒店,海鲜美食街,自然与人文景观融合]
      金湾区金海岸大道: [新兴商业街区,年轻人群聚集,潮流服饰多样,美食餐厅丰富,休闲娱乐多样,夜生活精彩纷呈]
      斗门区井岸镇中心路: [传统商业街区,特色小吃丰富,传统店铺众多,文化氛围浓厚,游客络绎不绝,交通便利快捷]
      横琴新区横琴大道: [现代商业街区,高端品牌云集,商务办公集中,美食餐厅林立,休闲娱乐丰富,交通便利快捷]

  浙江省: 
    杭州市: 
      上城区南宋御街: [历史文化街区,传统手工艺,特色小吃丰富,宋代建筑风貌,游客络绎不绝,文化活动频繁]
      西湖区文三路: [科技创业街区,电子产品集中,互联网公司多,创意产业聚集,年轻人群喜爱,交通便捷]
      拱墅区武林路: [时尚购物天堂,品牌旗舰店多,潮流服饰多样,美食餐厅林立,夜生活精彩纷呈,购物体验优越]
      滨江区星光大道: [现代商业街区,高端品牌云集,商务办公集中,美食餐厅林立,休闲娱乐丰富,交通便利快捷]
      余杭区梦想小镇: [创新孵化中心,科技企业聚集,创业氛围浓厚,文化活动丰富,年轻人群聚集,交通便捷快速]

    宁波市: 
      海曙区天一广场: [繁华商业中心,品牌旗舰店多,美食餐厅林立,文化活动频繁,交通便捷快速,购物体验优越]
      江东区东部新城: [现代商业街区,高端品牌云集,商务办公集中,美食餐厅林立,休闲娱乐丰富,交通便利快捷]
      江北区慈城古镇: [历史街区风貌,特色小吃丰富,传统店铺众多,文化氛围浓厚,游客络绎不绝,交通便利快捷]
      鄞州区南部商务区: [新兴商业街区,年轻人群聚集,潮流服饰多样,美食餐厅丰富,休闲娱乐多样,夜生活精彩纷呈]
      北仑区新碶老街: [传统商业街区,特色小吃丰富,传统店铺众多,文化氛围浓厚,游客络绎不绝,交通便利快捷]

    温州市: 
      鹿城区五马街: [历史文化街区,特色小吃丰富,传统店铺众多,文化氛围浓厚,游客络绎不绝,交通便利快捷]
      瓯海区温州大道: [现代商业街区,高端品牌云集,商务办公集中,美食餐厅林立,休闲娱乐丰富,交通便利快捷]
      龙湾区永强大道: [新兴商业街区,年轻人群聚集,潮流服饰多样,美食餐厅丰富,休闲娱乐多样,夜生活精彩纷呈]
      瑞安县玉海步行街: [传统商业街区,特色小吃丰富,传统店铺众多,文化氛围浓厚,游客络绎不绝,交通便利快捷]
      乐清市乐成镇中心街: [县城繁华地带,商业活动频繁,特色小吃多样,日常用品齐全,交通便利快捷,市民生活便利]

    嘉兴市: 
      南湖区中山路: [繁华商业中心,品牌旗舰店多,美食餐厅林立,文化活动频繁,交通便捷快速,购物体验优越]
      秀洲区王江泾古镇: [历史街区风貌,特色小吃丰富,传统店铺众多,文化氛围浓厚,游客络绎不绝,交通便利快捷]
      嘉善县魏塘镇中山东路: [传统商业街区,特色小吃丰富,传统店铺众多,文化氛围浓厚,游客络绎不绝,交通便利快捷]
      海盐县武原镇海滨路: [新兴商业街区,年轻人群聚集,潮流服饰多样,美食餐厅丰富,休闲娱乐多样,夜生活精彩纷呈]
      桐乡市濮院镇工贸大道: [现代商业街区,高端品牌云集,商务办公集中,美食餐厅林立,休闲娱乐丰富,交通便利快捷]

    绍兴市: 
      越城区鲁迅故里: [历史文化街区,特色小吃丰富,传统店铺众多,文化氛围浓厚,游客络绎不绝,交通便利快捷]
      柯桥区柯桥轻纺城: [专业市场中心,纺织品交易活跃,商业服务完善,物流便捷高效,人流如织不绝,购物选择多样]
      上虞区百官镇江东路: [新兴商业街区,年轻人群聚集,潮流服饰多样,美食餐厅丰富,休闲娱乐多样,夜生活精彩纷呈]
      诸暨市暨阳街道东一路: [县城繁华地带,商业活动频繁,特色小吃多样,日常用品齐全,交通便利快捷,市民生活便利]
      嵊州市剡湖街道嵊州大道: [城市主干道,商业活动繁荣,品牌店铺众多,美食餐厅林立,公共交通发达,市民出行方便]

  山东省: 
    济南市: 
      历下区泉城路: [历史文化街区,特色小吃丰富,传统店铺众多,文化氛围浓厚,游客络绎不绝,交通便利快捷]
      市中区经四路: [繁华商业中心,品牌旗舰店多,美食餐厅林立,文化活动频繁,交通便捷快速,购物体验优越]
      槐荫区纬十二路: [新兴商业街区,年轻人群聚集,潮流服饰多样,美食餐厅丰富,休闲娱乐多样,夜生活精彩纷呈]
      天桥区北园大街: [商业繁华地带,电子产品集中,时尚服饰多样,人流如织不绝,物流便捷高效,购物选择多样]
      历城区洪楼广场: [城市主干道,商业活动繁荣,品牌店铺众多,美食餐厅林立,公共交通发达,市民出行方便]

    青岛市: 
      市南区香港中路: [繁华商业中心,品牌旗舰店多,美食餐厅林立,文化活动频繁,交通便捷快速,购物体验优越]
      市北区台东步行街: [传统商业街区,特色小吃丰富,传统店铺众多,文化氛围浓厚,游客络绎不绝,交通便利快捷]
      崂山区青岛国际啤酒城: [啤酒文化节庆,国际美食丰富,娱乐项目多样,文化活动频繁,游客络绎不绝,交通便利快捷]
      李沧区李村步行街: [新兴商业街区,年轻人群聚集,潮流服饰多样,美食餐厅丰富,休闲娱乐多样,夜生活精彩纷呈]
      黄岛区金沙滩路: [沿海风光旖旎,浪漫爱情圣地,海滩休闲娱乐,高端度假酒店,海鲜美食街,自然与人文景观融合]

    烟台市: 
      芝罘区南大街: [繁华商业中心,品牌旗舰店多,美食餐厅林立,文化活动频繁,交通便捷快速,购物体验优越]
      莱山区观海路: [现代商业街区,高端品牌云集,商务办公集中,美食餐厅林立,休闲娱乐丰富,交通便利快捷]
      开发区长江路: [新兴商业街区,年轻人群聚集,潮流服饰多样,美食餐厅丰富,休闲娱乐多样,夜生活精彩纷呈]
      牟平区正阳路: [传统商业街区,特色小吃丰富,传统店铺众多,文化氛围浓厚,游客络绎不绝,交通便利快捷]
      福山区永安街: [县城繁华地带,商业活动频繁,特色小吃多样,日常用品齐全,交通便利快捷,市民生活便利]

    潍坊市: 
      奎文区东风东街: [繁华商业中心,品牌旗舰店多,美食餐厅林立,文化活动频繁,交通便捷快速,购物体验优越]
      潍城区向阳路: [历史街区风貌,特色小吃丰富,传统店铺众多,文化氛围浓厚,游客络绎不绝,交通便利快捷]
      坊子区坊城东街: [新兴商业街区,年轻人群聚集,潮流服饰多样,美食餐厅丰富,休闲娱乐多样,夜生活精彩纷呈]
      寒亭区民主街: [县城繁华地带,商业活动频繁,特色小吃多样,日常用品齐全,交通便利快捷,市民生活便利]
      高新开发区北海路: [现代商业街区,高端品牌云集,商务办公集中,美食餐厅林立,休闲娱乐丰富,交通便利快捷]

    威海市: 
      环翠区新威路: [繁华商业中心,品牌旗舰店多,美食餐厅林立,文化活动频繁,交通便捷快速,购物体验优越]
      文登区文山路: [历史街区风貌,特色小吃丰富,传统店铺众多,文化氛围浓厚,游客络绎不绝,交通便利快捷]
      荣成市成山大道: [沿海风光旖旎,浪漫爱情圣地,海滩休闲娱乐,高端度假酒店,海鲜美食街,自然与人文景观融合]
      乳山市胜利街: [新兴商业街区,年轻人群聚集,潮流服饰多样,美食餐厅丰富,休闲娱乐多样,夜生活精彩纷呈]
      高技术产业开发区文化西路: [现代商业街区,高端品牌云集,商务办公集中,美食餐厅林立,休闲娱乐丰富,交通便利快捷]

  福建省: 
    福州市: 
      鼓楼区三坊七巷: [历史文化街区,传统建筑保存,特色小吃丰富,手工艺品独特,文化氛围浓厚,游客络绎不绝]
      台江区中亭街: [繁华商业中心,品牌旗舰店多,美食餐厅林立,文化活动频繁,交通便捷快速,购物体验优越]
      晋安区东二环泰禾广场: [现代商业街区,高端品牌云集,商务办公集中,美食餐厅林立,休闲娱乐丰富,交通便利快捷]
      仓山区万达广场: [新兴商业街区,年轻人群聚集,潮流服饰多样,美食餐厅丰富,休闲娱乐多样,夜生活精彩纷呈]
      马尾区马尾古镇: [历史街区风貌,特色小吃丰富,传统店铺众多,文化氛围浓厚,游客络绎不绝,交通便利快捷]

    厦门市: 
      思明区中山路: [繁华商业中心,品牌旗舰店多,美食餐厅林立,文化活动频繁,交通便捷快速,购物体验优越]
      湖里区SM城市广场: [现代商业街区,高端品牌云集,商务办公集中,美食餐厅林立,休闲娱乐丰富,交通便利快捷]
      集美区集美学村: [历史文化街区,学府氛围浓厚,特色小吃丰富,文化活动频繁,游客络绎不绝,交通便利快捷]
      海沧区阿罗海城市广场: [新兴商业街区,年轻人群聚集,潮流服饰多样,美食餐厅丰富,休闲娱乐多样,夜生活精彩纷呈]
      同安区同安老街: [传统商业街区,特色小吃丰富,传统店铺众多,文化氛围浓厚,游客络绎不绝,交通便利快捷]

    泉州市: 
      鲤城区西街: [历史文化街区,佛教文化浓厚,特色小吃丰富,手工艺品独特,文化氛围浓厚,游客络绎不绝]
      丰泽区浦西万达广场: [现代商业街区,高端品牌云集,商务办公集中,美食餐厅林立,休闲娱乐丰富,交通便利快捷]
      洛江区万安街道: [新兴商业街区,年轻人群聚集,潮流服饰多样,美食餐厅丰富,休闲娱乐多样,夜生活精彩纷呈]
      晋江市五店市: [传统商业街区,特色小吃丰富,传统店铺众多,文化氛围浓厚,游客络绎不绝,交通便利快捷]
      石狮市宝盖镇: [县城繁华地带,商业活动频繁,特色小吃多样,日常用品齐全,交通便利快捷,市民生活便利]

    漳州市: 
      芗城区中山公园周边: [繁华商业中心,品牌旗舰店多,美食餐厅林立,文化活动频繁,交通便捷快速,购物体验优越]
      龙文区万达广场: [现代商业街区,高端品牌云集,商务办公集中,美食餐厅林立,休闲娱乐丰富,交通便利快捷]
      漳浦县旧镇镇: [传统商业街区,特色小吃丰富,传统店铺众多,文化氛围浓厚,游客络绎不绝,交通便利快捷]
      云霄县云陵镇: [县城繁华地带,商业活动频繁,特色小吃多样,日常用品齐全,交通便利快捷,市民生活便利]
      东山县铜陵镇: [沿海风光旖旎,浪漫爱情圣地,海滩休闲娱乐,高端度假酒店,海鲜美食街,自然与人文景观融合]

    莆田市: 
      城厢区文献路: [繁华商业中心,品牌旗舰店多,美食餐厅林立,文化活动频繁,交通便捷快速,购物体验优越]
      涵江区涵东街道: [新兴商业街区,年轻人群聚集,潮流服饰多样,美食餐厅丰富,休闲娱乐多样,夜生活精彩纷呈]
      荔城区荔城大道: [传统商业街区,特色小吃丰富,传统店铺众多,文化氛围浓厚,游客络绎不绝,交通便利快捷]
      仙游县鲤城街道: [县城繁华地带,商业活动频繁,特色小吃多样,日常用品齐全,交通便利快捷,市民生活便利]
      秀屿区笏石镇: [沿海风光旖旎,浪漫爱情圣地,海滩休闲娱乐,高端度假酒店,海鲜美食街,自然与人文景观融合]
